import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const v2Dir = resolve(testDir, "..");
const scriptPath = resolve(v2Dir, "scripts", "browser_use_creative_generator_e2e.py");

test("browser-use creative generator e2e keeps browser session alive across stages", () => {
  const source = readFileSync(scriptPath, "utf-8");
  assert.match(source, /HEADLESS = \(os\.getenv\('BROWSER_USE_HEADLESS', '0'\)/);
  assert.match(source, /keep_alive=True/);
  assert.match(source, /BrowserProfile\(\s*headless=HEADLESS,/);
  assert.match(source, /tempfile\.mkdtemp\(prefix='buildwise-browser-use-'\)/);
  assert.match(source, /user_data_dir=fresh_profile_dir/);
  assert.match(source, /BROWSER_USE_PROVIDER = os\.getenv\('BROWSER_USE_PROVIDER', 'anthropic'\)/);
  assert.match(source, /ChatOpenAI/);
  assert.match(source, /ChatDeepSeek/);
  assert.match(source, /if BROWSER_USE_PROVIDER == 'deepseek'/);
  assert.match(source, /if BROWSER_USE_PROVIDER == 'openai-compatible'/);
  assert.match(source, /prefer_minimax = BROWSER_USE_PROVIDER == 'minimax'/);
  assert.match(source, /prefer_dom_only = BROWSER_USE_PROVIDER == 'deepseek'/);
  assert.match(source, /os\.getenv\('MINIMAX_API_KEY'\)/);
  assert.match(source, /os\.getenv\('MINIMAX_API_BASE'\)/);
  assert.match(source, /os\.getenv\('MINIMAX_MODEL'\)/);
  assert.match(source, /def build_fallback_llm\(\)/);
  assert.doesNotMatch(source, /fallback_llm=fallback_llm/);
  assert.match(source, /os\.getenv\('DEEPSEEK_API_KEY'\)/);
  assert.match(source, /deepseek-chat/);
  assert.match(source, /use_vision=False, suffix='dom-fallback'/);
  assert.match(source, /use_vision=not prefer_dom_only, suffix='vision' if not prefer_dom_only else 'dom-primary'/);
  assert.match(source, /if not ok and fallback_llm is not None:/);
  assert.match(source, /payload\.get\('iterations'\)/);
  assert.match(source, /v11_analysis_drawer/);
  assert.match(source, /drawer_to_chat/);
  assert.match(source, /switch_to_v1/);
  assert.match(source, /chat_followup_v1/);
  assert.match(source, /无论.手机验证码.是否已经选中，都先点击一次.手机验证码.标签/);
  assert.match(source, /不要再查找.查看变更映射.按钮/);
  assert.match(source, /顶部不应再出现常驻的变更影响提醒卡/);
  assert.match(source, /不要点击.返回项目管理.或离开当前页面/);
  assert.match(source, /优先点击该项目区域附近的.查看全部.按钮展开项目版本面板/);
  assert.match(source, /len\(results\) == 14/);
});
