import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDir = dirname(fileURLToPath(import.meta.url));
const v2Dir = resolve(testDir, "..");
const scriptPath = resolve(v2Dir, "scripts", "setup-creative-generator-demo.mjs");

test("creative generator setup script resumes from completed artifacts and retries transient llm payload failures", () => {
  const source = readFileSync(scriptPath, "utf-8");
  assert.match(source, /const FORCE_ARTIFACTS = new Set/);
  assert.match(source, /const FORCE_ITERATION_IDS = new Set/);
  assert.match(source, /const ARTIFACT_OUTPUT_TEMPLATES = \{/);
  assert.match(source, /const COMPOSED_LLM_ARTIFACTS = new Set\(\["prototype-preview", "frontend-code", "backend-code"\]\)/);
  assert.match(source, /function logSetup\(message, payload\)/);
  assert.match(source, /function extractJsonObject\(raw\)/);
  assert.match(source, /function buildPrototypeHtml\(spec\)/);
  assert.match(source, /function buildFrontendCodeArtifact\(spec\)/);
  assert.match(source, /function buildBackendCodeArtifact\(spec\)/);
  assert.match(source, /function buildDefaultStructuredSpec\(artifactId\)/);
  assert.match(source, /function buildDeterministicComposedArtifact\(artifactId\)/);
  assert.match(source, /const DETERMINISTIC_TEXT_FALLBACKS = \{/);
  assert.match(source, /function buildDeterministicTextFallback\(artifactId\)/);
  assert.match(source, /async function generateComposedArtifact\(artifactId, effectiveMessage\)/);
  assert.match(source, /\[setup-demo\]/);
  assert.match(source, /# 分析报告/);
  assert.match(source, /## 目标用户/);
  assert.match(source, /## 问题定义/);
  assert.match(source, /## 核心场景/);
  assert.match(source, /"frontend-code": \[/);
  assert.match(source, /export function CreativeGeneratorPage\(\)/);
  assert.match(source, /"backend-code": \[/);
  assert.match(source, /registerCreativeRoutes/);
  assert.match(source, /function buildStructuredArtifactPrompt\(artifactId, prompt\)/);
  assert.match(source, /function preferredDirectMaxTokens\(artifactId\)/);
  assert.match(source, /artifactId === "frontend-code" \|\| artifactId === "backend-code"/);
  assert.match(source, /return 12000/);
  assert.match(source, /async function continueWithDirectLlm\(artifactId, previousContent\)/);
  assert.match(source, /不要写前言、说明、解释、确认语或摘要/);
  assert.match(source, /必须完整覆盖下面模板中的全部章节/);
  assert.match(source, /BUILDWISE_FORCE_ITERATION_IDS/);
  assert.match(source, /BUILDWISE_FORCE_ARTIFACTS/);
  assert.match(source, /const DEMO_PHONE = process\.env\.BUILDWISE_DEMO_LOGIN_PHONE \|\| "13800138000"/);
  assert.match(source, /const LLM_PROVIDER = \(\(\) =>/);
  assert.match(source, /return LLM_API_BASE\.includes\("\/anthropic"\) \? "anthropic-compatible" : "openai-compatible"/);
  assert.match(source, /for \(let attempt = 1; attempt <= 5; attempt \+= 1\)/);
  assert.match(source, /missing reply\|invalid payload/i);
  assert.match(source, /invalid direct llm payload/);
  assert.match(source, /let directLlmFailure = ""/);
  assert.match(source, /直连交付物生成失败：\$\{directLlmFailure\}/);
  assert.match(source, /let accessToken = ""/);
  assert.match(source, /Authorization: `Bearer \$\{accessToken\}`/);
  assert.match(source, /async function ensureAuthToken\(\)/);
  assert.match(source, /requestJson\("\/api\/v1\/auth\/sms\/request"/);
  assert.match(source, /requestJson\("\/api\/v1\/auth\/sms\/verify"/);
  assert.match(source, /sms debug code unavailable for setup authentication/);
  assert.match(source, /await ensureAuthToken\(\)/);
  assert.match(source, /LLM_PROVIDER === "anthropic-compatible" \? `\$\{LLM_API_BASE\}\/v1\/messages` : `\$\{LLM_API_BASE\}\/chat\/completions`/);
  assert.match(source, /Authorization: `Bearer \$\{apiKey\}`/);
  assert.match(source, /return data\?\.choices\?\.\[0\]\?\.message\?\.content \|\| ""/);
  assert.match(source, /const structuredBaseMessage = buildStructuredArtifactPrompt\(artifactId, baseMessage\)/);
  assert.match(source, /await createMessage\(iteration\.id, "user", structuredBaseMessage\)/);
  assert.match(source, /logSetup\("artifact-start"/);
  assert.match(source, /logSetup\("artifact-direct-attempt"/);
  assert.match(source, /logSetup\("artifact-direct-continuation"/);
  assert.match(source, /logSetup\("artifact-direct-continuation-failed"/);
  assert.match(source, /logSetup\("artifact-coach-attempt"/);
  assert.match(source, /logSetup\("artifact-committed"/);
  assert.match(source, /COMPOSED_LLM_ARTIFACTS\.has\(artifactId\)/);
  assert.match(source, /logSetup\("artifact-composed-direct-failed"/);
  assert.match(source, /logSetup\("artifact-composed-fallback"/);
  assert.match(source, /logSetup\("artifact-composed-hard-fallback"/);
  assert.match(source, /logSetup\("artifact-text-fallback"/);
  assert.match(source, /intent: "deterministic-text-fallback"/);
  assert.match(source, /intent: "composed-direct"/);
  assert.match(source, /intent: "direct"/);
  assert.match(source, /if \(!COMPOSED_LLM_ARTIFACTS\.has\(artifactId\)\) \{\s*content = await continueContent/);
  assert.match(source, /directLlmGenerate\(effectiveMessage, preferredDirectMaxTokens\(artifactId\)\)/);
  assert.match(source, /function shouldSeedConversation\(artifacts\)/);
  assert.match(source, /function selectPendingSteps\(iterationId, steps, artifacts\)/);
  assert.match(source, /const pendingSteps = selectPendingSteps\(iteration\.id, steps, existingArtifacts\)/);
  assert.match(source, /const forcedIteration = FORCE_ITERATION_IDS\.size === 0 \|\| FORCE_ITERATION_IDS\.has\(iterationId\)/);
  assert.match(source, /\(forcedArtifact && forcedIteration\) \|\| !completed\.has\(artifactId\)/);
  assert.match(source, /这是用于流程验证的交付物重建，不是阶段推进。请忽略当前迭代所处阶段，直接输出交付物/);
  assert.match(source, /llm\?\.reachable !== true/);
  assert.doesNotMatch(source, /!String\(llm\?\.model \|\| ""\)\.trim\(\)/);
  assert.match(source, /model: LLM_MODEL \|\| llm\.model \|\| ""/);
  assert.match(source, /baseUrl: LLM_API_BASE \|\| llm\.baseUrl \|\| ""/);
  assert.match(source, /分析报告。使用 Markdown 标题分节，必须完整包含：目标用户、问题定义、核心场景、本轮纳入项、本轮排除项、交互原则、关键风险、待确认点/);
  assert.match(source, /继承差异分析报告。使用 Markdown 标题分节，必须完整包含：继承不变项、本轮新增项、业务规则变化、影响范围、受影响工程对象、回归关注点、待确认点/);
  assert.match(source, /直接输出完整正文，不要给流程说明或待处理摘要/);
  assert.match(source, /保持正常对话回复，但正文必须包含一份完整可渲染的 HTML 原型/);
  assert.match(source, /正文必须包含完整的 TypeScript\/React 代码/);
  assert.doesNotMatch(source, /只返回完整 HTML/);
});
